[project]
name = "litestar-resttest"
version = "1.0.0" # future contributors, no real need to change this
requires-python = ">=3.12"
dependencies = [
    "hypercorn>=0.17.3",
    "litestar>=2.16.0",
    "pydantic>=2.11.7",
]
