version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./assets:/app/assets:ro
    env_file:
      - .env
    environment:
      - TZ=UTC
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp